### ISSUE TITLE
Extra BiGRU in model.py?

### ISSUE THREAD

**Issue by keithhans** [YerevaNN/R-NET-in-Keras#15]
I can't find it in the paper.  Is it intentional or an accident?

Line 116 to 118:
        gP = Bidirectional(GRU(units=H,
                               return_sequences=True,
                               unroll=unroll)) (hP)

**Comment by mahnerak** [comment]
In our blogpost we mentioned that:
https://yerevann.github.io/2017/08/25/challenges-of-reproducing-r-net-neural-network-using-keras/
> In Section 4.2 of the technical report the authors write that after submitting their paper to ACL they made one more modification. **They have added another bidirectional GRU on top of hP before feeding it to PointerGRU**.

From technical report, Section 4.2:
> After the original self-matching layer of the passage, **we utilize bi-directional GRU to deeply integrate the matching results before feeding them into answer pointer layer**. It helps to further propagate the information aggregated by self-matching of the passage.

**Comment by keithhans** [comment]
Thanks a lot for clarification!
